### ISSUE TITLE
calendar not showing in debian 10

### ISSUE THREAD

**Issue by graymind75** [yousefvand/plasmoid-persian-calendar#7]
Hi
i can't use the widget due to this error, please guide me how can i solve this problem
thanks
```
Error loading QML file: file:///home/graymind75/.local/share/plasma/plasmoids/org.kde.plasma.persian-calendar/contents/ui/main.qml:7:1: Script file:///home/graymind75/.local/share/plasma/plasmoids/org.kde.plasma.persian-calendar/contents/lib/pdp.js unavailable
file:///home/graymind75/.local/share/plasma/plasmoids/org.kde.plasma.persian-calendar/contents/lib/pdp.js:163:16: Expected token `:'
```

**Comment by yousefvand** [comment]
Hello

- This is probably due to your KDE version and you need an update (Javascript engine doesn't recognize some command(s)). What is the output of this command: 

`plasmashell --version`

(currently on archlinux mine is `5.20.4`).

- What is the output of this command: `kf5-config --version`
(mine: 
```
Qt: 5.15.2
KDE Frameworks: 5.76.0
kf5-config: 1.0
```
)

**Comment by graymind75** [comment]
yes, the problem is plasma-shell and qt was not up to date in latest Debian version
after switch to fedora and plasma 5.20 it's all OK

thanks
